version = "1.0"
[main]
name = "InvoicNinja configuration"

    [main.config]
    name = "Configuration Options"

        [main.config.default_from_email_address]
        ask.en = "Choose from which mail address emails will be sent"
        ask.fr = "Choisissez à partir de quelle adresse e-mail les e-mails seront envoyés"
        help = "Default email address to use for various automated emails."
        bind = "MAIL_FROM_ADDRESS:__INSTALL_DIR__/.env"

        [main.config.default_from_email_name]
        ask.en = "Choose what name will be displayed when InvoiceNinja sends mails"
        ask.fr = "Choisissez quel nom sera affiché lorsque InvoiceNinja enverra des e-mails"
        help = "Default name address to use for various automated names."
        bind = "MAIL_FROM_NAME:__INSTALL_DIR__/.env"
